"""
LLM-powered factor hypothesis generator.

Supports multiple backends:
  - Moonshot Kimi K2.5 (default)
  - Anthropic Claude Sonnet 4.5

Implements the paper's Algorithm 1: agentic closed-loop factor discovery.
The agent generates factor hypotheses with economic rationale (Chain-of-Thought),
receives structured feedback from backtesting, and refines its search strategy
via memory-guided iteration.
"""

from __future__ import annotations

import json
import logging
import os
import time
from dataclasses import dataclass, field, asdict
from typing import Any

from dotenv import load_dotenv
from openai import OpenAI

# Load .env from project root (override empty shell vars)
load_dotenv(override=True)

from lib.factor_grammar import (
    FactorExpression,
    grammar_description,
    parse_expression,
)
from lib.factor_evaluator import FactorMetrics

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

@dataclass
class FactorHypothesis:
    """A single hypothesis generated by the agent."""

    round: int
    economic_rationale: str
    formula: str
    expression: FactorExpression | None = None

    def to_dict(self) -> dict:
        return {
            "round": self.round,
            "economic_rationale": self.economic_rationale,
            "formula": self.formula,
        }


@dataclass
class RoundRecord:
    """Structured log entry for one round of the discovery loop."""

    round: int
    hypothesis: str
    formula: str
    metrics: dict | None = None
    decision: str = ""
    reason: str = ""
    error: str | None = None

    def to_dict(self) -> dict:
        return {k: v for k, v in asdict(self).items() if v is not None}


@dataclass
class AgentMemory:
    """Accumulated evidence across rounds — the agent's state representation."""

    rounds: list[RoundRecord] = field(default_factory=list)
    promoted_formulas: list[str] = field(default_factory=list)
    retired_formulas: list[str] = field(default_factory=list)

    def add_round(self, record: RoundRecord) -> None:
        self.rounds.append(record)
        if record.decision == "promote":
            self.promoted_formulas.append(record.formula)
        elif record.decision == "retire":
            self.retired_formulas.append(record.formula)

    def to_prompt_context(self) -> str:
        """Format memory as context for the LLM prompt."""
        if not self.rounds:
            return "No prior rounds. This is the first iteration."

        lines = [f"## Prior Discovery Rounds ({len(self.rounds)} total)\n"]

        # Summarize promoted factors
        if self.promoted_formulas:
            lines.append(f"### Promoted factors ({len(self.promoted_formulas)}):")
            for f in self.promoted_formulas:
                lines.append(f"  - `{f}`")
            lines.append("")

        # Show recent rounds in detail (last 5)
        recent = self.rounds[-5:]
        lines.append(f"### Recent rounds (last {len(recent)}):")
        for r in recent:
            status = f"[{r.decision.upper()}]" if r.decision else "[ERROR]"
            lines.append(f"\nRound {r.round} {status}:")
            lines.append(f"  Rationale: {r.hypothesis[:200]}")
            lines.append(f"  Formula: `{r.formula}`")
            if r.metrics:
                m = r.metrics
                lines.append(
                    f"  Metrics: IC t-stat={m.get('ic_t_stat', 0):.2f}, "
                    f"Sharpe={m.get('ls_sharpe', 0):.2f}, "
                    f"Ret={m.get('ls_annual_return', 0):.2%}"
                )
            if r.error:
                lines.append(f"  Error: {r.error}")
            lines.append(f"  Decision: {r.reason}")

        # Guidance
        lines.append("\n### Search guidance:")
        if self.retired_formulas:
            lines.append(f"  - {len(self.retired_formulas)} formulas retired — avoid similar patterns")
        lines.append("  - Exploit: try variants of promoted factors (different windows, transforms)")
        lines.append("  - Explore: try new signal families not yet attempted")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are an autonomous quantitative researcher discovering alpha factors for U.S. financial sector equities (XLF ETF components).

**Objective**: Find factors that predict 10-day forward returns for financial stocks (banks, insurance, capital markets, REITs).
**Target**: Sharpe ratio >= 1.2 on a long-short portfolio. This is a HIGH bar — you must be creative and precise.

Your task: propose ONE new factor hypothesis per round. For each hypothesis, you must provide:
1. **Economic rationale** (2-3 sentences): WHY this signal should predict 10-day returns specifically for financial sector stocks. Ground it in:
   - Market microstructure (order flow, liquidity, bid-ask dynamics)
   - Behavioral finance (overreaction, underreaction, sentiment)
   - Technical analysis (trend, mean-reversion, momentum, support/resistance)
   - Financial sector-specific drivers (yield curve sensitivity, credit spreads, regulatory events)
2. **Formula**: A mathematical expression using the grammar below.

{grammar}

## High-priority signal ideas (from prior research on financials):
- **52-week high momentum**: Stocks near 52w highs continue outperforming. Combine `distance_from_52w_high` with confirmation signals.
- **Multi-horizon momentum spread**: Difference between long-term (60d) and short-term (10d) momentum isolates trend vs noise.
- **Volume-confirmed trend**: High volume_ratio combined with positive momentum = institutional conviction.
- **Volatility regime**: Low-vol stocks outperform in financials; `neg(rank(realized_vol))` as a baseline.
- **Beta timing**: Rising beta (`diff(beta_60d, 20)`) during uptrends signals risk appetite.
- **RSI + trend filter**: RSI works better when combined with trend (price_to_sma200), not standalone.
- **Mean-reversion in high-vol names**: `neg(return_10d)` works for high-vol financials only.
- **Intermediate momentum (20d)**: Often the sweet spot between noise and staleness for financials.
- **Interaction effects**: Combine primitives multiplicatively — e.g., momentum * neg(vol) * volume_ratio.

## Rules:
- Each formula must be computable from daily price, volume, and market return data
- NO look-ahead bias: all operators use only past/present data
- Maximum expression depth: 4 (you can nest up to 4 levels)
- Factors are evaluated on a 10-day holding period — favor signals with persistence over ~2 weeks
- Each factor should capture a DISTINCT economic mechanism from previously promoted factors
- Learn from prior failures: NEVER repeat a retired formula pattern
- Explore: try NEW signal families not yet attempted in prior rounds
- The universe is ~65 financial sector stocks — cross-sectional operators work but the cross-section is narrower

## Output format (strict JSON):
```json
{{
  "economic_rationale": "...",
  "formula": "..."
}}
```

Respond with ONLY the JSON block, no other text."""


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

def _extract_json(text: str) -> str:
    """Extract JSON object from LLM response, handling markdown blocks, thinking, etc."""
    import re as _re

    # Try markdown code blocks first
    if "```json" in text:
        return text.split("```json")[1].split("```")[0].strip()
    if "```" in text:
        blocks = text.split("```")
        for i in range(1, len(blocks), 2):
            block = blocks[i].strip()
            # Skip language identifiers on first line
            if block and block[0] != "{":
                lines = block.split("\n", 1)
                if len(lines) > 1:
                    block = lines[1].strip()
            if block.startswith("{"):
                return block

    # Find JSON object directly via brace matching
    match = _re.search(r"\{[^{}]*\"economic_rationale\"[^{}]*\"formula\"[^{}]*\}", text, _re.DOTALL)
    if match:
        return match.group(0)

    # Last resort: find first { to last }
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        return text[start:end + 1]

    raise ValueError(f"Could not extract JSON from LLM response: {text[:200]}...")


class FactorAgent:
    """LLM-based factor hypothesis generator with memory.

    Supports two backends selected via `backend`:
      - "moonshot" (default): Kimi K2.5 via OpenAI-compatible API
      - "anthropic": Claude Sonnet 4.5 via Anthropic SDK
    """

    BACKENDS = {
        "moonshot": {
            "base_url": "https://api.moonshot.ai/v1",
            "model": "kimi-k2.5",
            "env_key": "MOONSHOT_API_KEY",
            "temperature": 1.0,
            "max_tokens": 4096,
        },
        "anthropic": {
            "base_url": "https://api.anthropic.com/v1",
            "model": "claude-sonnet-4-6",
            "env_key": "ANTHROPIC_API_KEY",
            "temperature": 0.8,
            "max_tokens": 2048,
        },
    }

    def __init__(
        self,
        backend: str = "moonshot",
        api_key: str | None = None,
        model: str | None = None,
    ):
        if backend not in self.BACKENDS:
            raise ValueError(f"Unknown backend '{backend}'. Choose from: {list(self.BACKENDS)}")

        cfg = self.BACKENDS[backend]
        self.backend = backend
        self.model = model or cfg["model"]
        self._temperature = cfg["temperature"]
        self._max_tokens = cfg["max_tokens"]

        resolved_key = api_key or os.environ.get(cfg["env_key"], "")
        if not resolved_key:
            raise ValueError(
                f"No API key found for backend '{backend}'. "
                f"Set {cfg['env_key']} or pass api_key=."
            )

        if backend == "anthropic":
            try:
                import anthropic
                self._anthropic_client = anthropic.Anthropic(api_key=resolved_key)
                self.client = None  # not using OpenAI client
            except ImportError:
                raise ImportError("pip install anthropic  — required for Claude backend")
        else:
            self.client = OpenAI(api_key=resolved_key, base_url=cfg["base_url"])
            self._anthropic_client = None

        self.memory = AgentMemory()
        self._system_prompt = SYSTEM_PROMPT.format(grammar=grammar_description())

    def _call_llm(self, user_prompt: str) -> str:
        """Dispatch to the configured LLM backend and return raw text."""
        if self.backend == "anthropic":
            response = self._anthropic_client.messages.create(
                model=self.model,
                system=self._system_prompt,
                messages=[{"role": "user", "content": user_prompt}],
                temperature=self._temperature,
                max_tokens=self._max_tokens,
            )
            # Anthropic returns list of content blocks
            parts = []
            for block in response.content:
                if block.type == "text":
                    parts.append(block.text)
            return "\n".join(parts).strip()
        else:
            # OpenAI-compatible (Moonshot, etc.)
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self._system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=self._temperature,
                max_tokens=self._max_tokens,
            )
            return (response.choices[0].message.content or "").strip()

    def generate_hypothesis(self, round_num: int, max_retries: int = 4) -> FactorHypothesis:
        """Generate a single factor hypothesis via the LLM.

        Returns a FactorHypothesis with the parsed expression, or raises on failure.
        """
        user_prompt = (
            f"Round {round_num}: Generate a new factor hypothesis.\n\n"
            f"{self.memory.to_prompt_context()}"
        )

        last_err = None
        for attempt in range(1, max_retries + 1):
            logger.info(f"Round {round_num}: Requesting hypothesis from {self.model}"
                        + (f" (attempt {attempt})" if attempt > 1 else ""))

            raw = self._call_llm(user_prompt)
            logger.debug(f"Raw LLM response ({len(raw)} chars): {raw[:500]}")

            try:
                json_str = _extract_json(raw)
                parsed = json.loads(json_str)
                rationale = parsed["economic_rationale"]
                formula = parsed["formula"]
                expression = parse_expression(formula)

                return FactorHypothesis(
                    round=round_num,
                    economic_rationale=rationale,
                    formula=formula,
                    expression=expression,
                )
            except (ValueError, json.JSONDecodeError, KeyError) as e:
                last_err = e
                logger.warning(f"Round {round_num} attempt {attempt} parse error: {e}")
                continue

        raise last_err  # type: ignore[misc]

    def record_round(self, record: RoundRecord) -> None:
        """Record the outcome of a round into agent memory."""
        self.memory.add_round(record)

    def get_audit_log(self) -> list[dict]:
        """Return full audit log as list of dicts."""
        return [r.to_dict() for r in self.memory.rounds]
